spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/login
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 303586329879-3n3pd4vf5iv3k28fgl6jjkpd75psj28a.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-id: s3mTXYUfoQCpRqPlNe8O
            client-secret: G6Q91JKRKo
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json의 형식으로 받는데 키값이 response



logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace # For Spring Boot 2.x, Hibernate 5
logging.level.root: info
logging:
  level:
    root: INFO
    example.login.service: DEBUG

